
--https://vertabelo.com/blog/creating-a-dwh-part-one-a-subscription-business-data-model/


DROP DATABASE IF EXISTS subscription_business;

CREATE DATABASE subscription_business;

USE subscription_business;


CREATE TABLE country
(
country_id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
coutry_name VRACHAR(50) UNIQUE NOT NULL,
created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


CREATE TABLE city
(
city_id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
country_id INT UNSIGNED NOT NULL,
city_name VRACHAR(50) NOT NULL,
postal_code CHAR(5) NOT NULL,
created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


CREATE TABLE product
(
product_id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
product_name VRACHAR(120) NOT NULL,
price DECIMAL(10, 2) NOT NULL,
created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);



CREATE TABLE document
(
document_id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
product_id INT UNSIGNED NOT NULL,
link TEXT NOT NULL,
created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


CREATE TABLE customer
(
customer_id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
fist_name
last_name
phone
email
username
password
confirmation_code
city_id
address_id
active
created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


CREATE TABLE subscription
(
subscription_id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
customer_id INT UNSIGNED NOT NULL,
start_date DATE NOT NULL,
end_date DATE DEFAULT NULL,
city_id
delivery_address
subscription_parameters JSON,
active
created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


CREATE TABLE current_product_subscription
(
id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
subscription_id INT UNSIGNED NOT NULL,
product_id INT UNSIGNED NOT NULL,
quantity SMALLINT UNSIGNED NOT NULL DEFAULT '1',
created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


CREATE TABLE delivery_status
(
delivery_status_id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
status_name VARCHAR(50) NOT NULL UNIQUE,
in_transit TINYINT(1) NOT NULL DEFAULT '0',
canceled TINYINT(1) NOT NULL DEFAULT '0',
delivered TINYINT(1) NOT NULL DEFAULT '0',
created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


CREATE TABLE delivery
(
delivery_id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
subscription_id INT UNSIGNED NOT NULL,
delivery_notes TEXT,
expected_delivery_time DATETIME,
city_id
delivery_address
current_delivery_status_id INT UNSIGNED NOT NULL,
created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


CREATE TABLE delivery_status_history
(
id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
delivery_id INT UNSIGNED NOT NULL,
delivery_status_id INT UNSIGNED NOT NULL,
status_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


CREATE TABLE delivery_product
(
id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
delivery_id INT UNSIGNED NOT NULL,
product_id INT UNSIGNED NOT NULL,
quantity
price
created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

